#!/bin/bash
#Extension Attribute to see if CheckinChecker is installed

if [[  -f "/private/var/tmp/CheckinChecker/CheckinChecker.sh" ]];
then
	echo "<result>Installed</result>"
else 
	echo "<result>Not Installed</result>"
fi
	
