#!/bin/bash
#This script is meant to be ran as a policy, daily trigger
# The CheckinChecker program pulls from this file to determine last checkin
function get_user {
	/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }'
}
currentuser=$(get_user)
today=$(date +”%Y-%b-%d”)
todayEpoch=$(date +”%s”)

#Every day, Jamf policy will run a policy to write to this file. 
echo $todayEpoch $today "recurring check-in from Jamf for user $currentuser" >> /private/tmp/CheckinChecker/JamfCheckinLog.txt
