#!/bin/bash
# Created by: Brooke Burdick brooburd@gmail.com
# This script must be ran once daily via jamf policy. It will log the latest checkin to calculate last checkin date. 
# v1 2024
###THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.###
#This script is meant to be ran as a policy, daily trigger
# The CheckinChecker program pulls from this file to determine last checkin
function get_user {
	/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }'
}

function checkin(){
	currentuser=$(get_user)
	today=$(date +”%Y-%b-%d”)
	todayEpoch=$(date +”%s”)
	
	#Every day, Jamf policy will run a policy to write to this file. 
	echo $todayEpoch $today "recurring check-in from Jamf for user $currentuser" > /private/var/tmp/CheckinChecker/JamfCheckinLog.txt
	
	echo "Checkin Complete $today"
}


if [[ -f  "/private/var/tmp/CheckinChecker" ]]
then	
checkin
else 
mkdir /private/var/tmp/CheckinChecker
checkin
fi
exit 0
